Export omeka
Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch pull request #101
Opened 2024-05-15 22:58 UTC by maehr

# Pull request

## Proposed changes

- Update metadata model
- Fix #100 

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [x] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [ ] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-15 23:02 UTC, maehr commented
@coderabbitai Read #100 again. It should have said update to v4.

2024-05-16 15:46 UTC, koilebeit requested changes
You use the omeka internal id. But as id we need the abb or m identifier, don't we? I don't know if it's just that, but the item pages are not found this way...

2024-05-16 15:46 UTC, koilebeit commented on .github/workflows/process_data.py
> +        "objectid": item["o:id"],
you are using the omeka internal id here. but it needs "our" id (dcterms:identifier)
```suggestion
        "objectid": extract_prop_value(item.get("dcterms:identifier", []), 10),
```
but of course this has consequences for line 201

2024-05-16 15:46 UTC, koilebeit commented on .github/workflows/process_data.py
> +        "objectid": media["o:id"],
see comment above
```suggestion
        "objectid": extract_prop_value(media.get("dcterms:identifier", []), 10),
```

2024-05-16 15:46 UTC, koilebeit commented on .github/workflows/process_data.py
> +        item_id = item["o:id"]
see comment above

2024-05-16 16:02 UTC, maehr commented
@koilebeit I'll try to fix this asap. Shouldn't be a biggy

2024-05-17 05:52 UTC, maehr commented
@koilebeit the csv must not contain quotation marks. Somehow the gallery worked but browse didn't. Thats why I didn't notice the bug. Now it builds locally.

2024-05-17 09:07 UTC, maehr commented on .github/workflows/process_data.py
> +        "object_location": local_image_path,
I did this on purpose. We should make sure first to have all the rights before we offer the originals. I'll add some documentation.
@coderabbitai open an issue for this

2024-05-17 09:18 UTC, koilebeit approved these changes
When we merge, however, only the objects from the new collection will be online

2024-05-21 15:27 UTC, koilebeit commented
If it is possible, the object_location should at least be specified correctly for the geodata, otherwise the new map view (in #99) will not work

2024-05-22 16:07 UTC, maehr commented
> When we merge, however, only the objects from the new collection will be online. And the display (especially the links) still contains the markdown

Do you want to fix this in the view rather than here?

2024-05-29 08:25 UTC, koilebeit commented
I noticed two more things:
1. the parent objects do not need an object_location. Should be a quick fix.
2. how do we deal with media appearing in several parent objects (e.g. the placeholder image)? In omeka this is easy, but in CB-CSV each objectid must be unique and can only have one parentid (see [https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/#metadata-conventions](https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/#metadata-conventions)). So in cb no n-m relationship is possible, only a 1-n relationship.

2024-05-29 08:58 UTC, maehr commented
> I noticed two more things:
> 
> 1. the parent objects do not need an object_location. Should be a quick fix.
> 2. how do we deal with media appearing in several parent objects (e.g. the placeholder image)? In omeka this is easy (although I have no idea how to do this in the omeka interface), but in CB-CSV each objectid must be unique and can only have one parentid (see https://collectionbuilder.github.io/cb-docs/docs/metadata/compound-objects/#metadata-conventions). So in cb no n-m relationship is possible, only a 1-n relationship.

Thanks for pointing out these bugs. I'll try something

2024-05-29 14:37 UTC, maehr commented
@koilebeit I fixed bug 1 and I figured out that even though the docs say differently, you can just add a second line copying over the media object and adjust the parent_id. It works. (It's not a nice workaround, but it serves the purpose, right?)

2024-06-03 08:02 UTC, merged