Subpage Navigation via Buttons
Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch pull request #170
Opened 2024-10-25 17:06 UTC by mtwente

# Pull request

## Proposed changes

* remove dropdowns from navbar, fixes #87 
  * `data.html`
    * turn *Datenarchiv* into its own button on `data.html`
    * remove separate *Quellcode* button (still available via a modal on `data.html`, could also be added to the footer if necessary).
  * `browse.html`
    * add button next to the filter bar for changing views to subjects, timeline and wordcloud. Fixes #146 
  * `timeline.html`
    * add button to the right for changing views to browse, subjects and wordcloud
    * remove separate button for selecting each year separately, since with more data, the dropdown menu is becoming longer than the Rhine). We could have the dropdown selection with centuries? But that would still be a large dropdown menu with the entries from Volume 1.
  * `subjects.html`
    * add button to the right for changing views to browse, timeline and wordcloud
  * `eras.html`
    * add button to the right for changing views to browse, timeline and subjects.
    * this button is centered on smaller screens for better visual appearance

* minor CSS improvements for `browse.html` regarding colouring and mobile view
* add "Ansicht umschalten", "Zeitachse", "Themen", "Epochen" as entries to `translations.yml` (ignored translations to Spanish...). I am not sure about the wording/translation for `browse`. Now it does not really fit to the other categories (verb vs. noun), but I did not have any good idea for phrasing at the moment.
 
## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-26 07:17 UTC, maehr requested changes
Hi @mtwente, thanks for your PR. It solves a lot of latent problems. Here's my 5 cents:

- [ ] On `/browse.html` please move the button group to the left and change the dropdown to a btn-group-toggle (see <https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons>). 
- [ ] On `/data.html` can you please add some text explaining the features (i.e. Zenodo Archive etc.)?
- [ ] Please review the feedback from coderabbitai. Especially the localisation seems to be inconsistent.

2024-10-26 07:17 UTC, maehr commented on _data/config-nav.csv
> -Portal,https://stadtgeschichtebasel.ch/,,true
Please revert the link to the Portal

2024-10-26 12:15 UTC, mtwente commented
> * [ ]  On `/browse.html` please move the button group to the left and change the dropdown to a btn-group-toggle (see https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons).

Like this? And on the other pages, I keep it as a dropdown and on the right side?

<img width="1624" alt="btn-group" src="https://github.com/user-attachments/assets/5071b6ff-3cfa-4550-9048-3ffbefa55581">

2024-10-26 14:10 UTC, maehr commented
> > * [ ]   On `/browse.html` please move the button group to the left and change the dropdown to a btn-group-toggle (see https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons).
> 
> Like this? And on the other pages, I keep it as a dropdown and on the right side?
> 
> <img alt="btn-group" width="1624" src="https://private-user-images.githubusercontent.com/127845092/380421671-5071b6ff-3cfa-4550-9048-3ffbefa55581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTIwOTAsIm5iZiI6MTcyOTk1MTc5MCwicGF0aCI6Ii8xMjc4NDUwOTIvMzgwNDIxNjcxLTUwNzFiNmZmLTNjZmEtNDU1MC05MDQ4LTNmZmJlZmE1NTU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNDA5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDMwY2U2Nzk3OWZkZTA5ODM3NTQ1ZWY5OTI5OTk2MDIyOTVkYWU0MzEyZGEzNzhhNjBlMTA4ZmRkNjliNWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xPHYba1xnp-IO2DwvEzJN-qlCX_q4JUNj3ZHE9ZTxhg">

This looks great! Thank you

2024-10-30 15:40 UTC, koilebeit approved these changes
I like it!! It's much better than before (everything in the main nav)

But we should have some kind of dropdown button on the timeline to jump to certain points in time, otherwise you scroll forever. But that can be a separate issue/pr

2024-10-30 16:47 UTC, maehr requested changes
Thanks again for the changes. Here are some minor remarks:

- [x] The buttons are sized differently on `browse` vs `cloud`, `list` and `timeline_edtf`
- [ ] The button group should have the same order on all pages
- [ ] The button group should have 4 elements, i.e. links to `browse`, `cloud`, `list` and `timeline_edtf`, on all pages
- [ ] The button group should indicate which button is active (aria and visually)

Thanks again. I really like it!

2024-10-30 17:12 UTC, mtwente commented
> - [ ] The buttons are sized differently on `browse` vs `cloud`, `list` and `timeline_edtf`

I made the buttons bigger on `browse` so it aligns with the search bar. Smaller buttons on `browse` look like they're detached from the rest of the content (as with the dropdown-button to the right in the current version of the page). On the other pages, I found large buttons to be too much.

I could change the search bar from large to small.

> - [ ] The button group should have 4 elements, i.e. links to `browse`, `cloud`, `list` and `timeline_edtf`, on all pages
> - [ ] The button group should have the same order on all pages

They do have the same order (Browse/Timeline/List/Eras), it's just that the active page/view is not shown as button (heading only). If I put all four buttons next to each other on all pages, it takes away quite a lot of space (especially on `browse`, there is very little space left for the search bar). That's also why I removed the button for the active view.

I could try moving the four buttons on their own row, stretch them across the whole page and have the search box below as-is, but that just creates oversized buttons.

2024-10-31 11:47 UTC, mtwente commented
Here are a few visual modifications:

Medium-sized buttons, to the left.
This way, the btn-group is vertically aligned with the filter box, but not with the btn-groups on the other pages.
<img width="1512" alt="btn-md-left" src="https://github.com/user-attachments/assets/ce6ada01-8c44-4034-b935-44808c283fc7">

Large-sized buttons, to the left.
<img width="1512" alt="btn-lg-left" src="https://github.com/user-attachments/assets/c36a1fe7-a6b4-49ff-9b95-c6aa54cc8ea9">

Medium-sized buttons, stretched on top.
<img width="1512" alt="btn-md-stretch" src="https://github.com/user-attachments/assets/e631aa9c-baeb-4ea4-a991-4284ffae3cc7">

2024-11-01 11:26 UTC, mtwente commented on _layouts/browse.html
> +          {{ site.data.translations._layouts['browse.html'].objects[site.lang] | default: 'Objects' }}
Translations for `objects`, `timeline`, `subjects` and `eras` are available in `_data/translations.yml` in lines 601 to 615.

2024-11-02 16:01 UTC, maehr approved these changes
@mtwente Thanks again for the improvement. On mobile we still run into problems (I also tested it on my native device)

![savage-poltergeist-g4r44g9gr6p2w4gg-4000 app github dev_browse html(iPhone 12 Pro)](https://github.com/user-attachments/assets/29fc4efa-832b-4473-8d9d-5d72ad859cac)

2024-11-02 16:03 UTC, mtwente commented
> @mtwente Thanks again for the improvement. On mobile we still run into problems (I also tested it on my native device)

Yes, I was just trying a few different solutions for that!

2024-11-05 10:47 UTC, maehr approved these changes
As discussed over the phone: Great PR, fix the localization either in this or in separate PR. If separate PR please open an issue.
cheers moritz

2024-11-05 10:47 UTC, maehr commented on _includes/js/table-js.html
> +                  text: 'Herunterladen',
@mtwente localization?

2024-11-06 13:39 UTC, merged