Filter data
Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch pull request #181
Opened 2024-11-10 09:58 UTC by maehr

# Pull request

- Add: better JSON data via <https://forschung.stadtgeschichtebasel.ch/assets/data/metadata.json>
- Fix: metadata export inconsistencies
- Feat: reordering of metadata in item view
- Feat: improve readability of javascript snippets

## Proposed changes

## Types of changes

- [ ] New feature (non-breaking change which adds functionality).
- [x] Enhancement (non-breaking change which enhances functionality)
- [ ] Bug Fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).

## Checklist

- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-11-10 10:29 UTC, maehr commented on .github/workflows/process_data.py
> +KEY_CREDENTIAL = "0v8AZu265B8EKkCCYOEkKQeOGBieejmy"
What a stupid mistake from my side. I revoked all keys and deleted the hard coded parts.

2024-11-12 07:45 UTC, koilebeit requested changes
Thank you very much for your PR. Looks very good. But we should also catch the following cases that may occur:
- a parent object does not (yet) have any media objects (e.g. [https://omeka.unibe.ch/admin/item/10891](https://omeka.unibe.ch/admin/item/10891))
- the media object has no derivatives in OMEKA (i don't know the reason for this yet). See [https://omeka.unibe.ch/admin/item/11412](https://omeka.unibe.ch/admin/item/11412)

2024-11-12 08:23 UTC, maehr commented
> Thank you very much for your PR. Looks very good. But we should also catch the following cases on the browse page that may occur:
> 
> * a parent object does not (yet) have any media objects (e.g. https://omeka.unibe.ch/admin/item/10891)
> * the media object has no derivatives in OMEKA (i don't know the reason for this yet). See https://omeka.unibe.ch/admin/item/11412

Thanks for pointing this out. I'll fix it.

The reason for the missing derivates are manual uploads because of the file size. We should report this to @flicksolutions directly.

2024-11-13 09:29 UTC, koilebeit reviewed
Now it works fine. But I actually liked the solution with the icon themes better. Now it always uses the same placeholder instead of the media-specific placeholder
https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/6fd1525ef348cf3819af2f9e7d4db4aee7bf5dc8/_includes/js/get-icon.js#L5
Now:
![image](https://github.com/user-attachments/assets/b517e869-594f-42ef-b56b-0bf3579225b5)
Before:
![image](https://github.com/user-attachments/assets/9ff9c93b-f60a-495a-8959-a503295baa33)

@mtwente, what do you think?

2024-11-13 09:44 UTC, maehr commented
> Now it works fine. But I actually liked the solution with the icon themes better. Now it always uses the same placeholder instead of the media-specific placeholder
> 
> https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/blob/6fd1525ef348cf3819af2f9e7d4db4aee7bf5dc8/_includes/js/get-icon.js#L5
> 
> 
> Now:
> ![image](https://private-user-images.githubusercontent.com/73133626/385689929-b517e869-594f-42ef-b56b-0bf3579225b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTEyNzgsIm5iZiI6MTczMTQ5MDk3OCwicGF0aCI6Ii83MzEzMzYyNi8zODU2ODk5MjktYjUxN2U4NjktNTk0Zi00MmVmLWI1NmItMGJmMzU3OTIyNWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5NDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDFlZDAzM2I4NzRjNzgwMjE4ZGQ2ZGI0Y2QzZmYzMzhjZDdlNjdjMmUxODE0ZTEwNjJhZDdlNjE3OTdlZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rg3oh9UIVgoImwjBYyf_L7o6_sxrUg9fTSTmKhfFv7g)
> Before:
> ![image](https://private-user-images.githubusercontent.com/73133626/385690269-9ff9c93b-f60a-495a-8959-a503295baa33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTEyNzgsIm5iZiI6MTczMTQ5MDk3OCwicGF0aCI6Ii83MzEzMzYyNi8zODU2OTAyNjktOWZmOWM5M2ItZjYwYS00OTVhLTg5NTktYTUwMzI5NWJhYTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5NDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODVhNmVmNzk0MTgyYWJiYzBjZGUzYzc2MDBjZWRlNTQ4NjY3MWQ4YWRjMDZhNGJiODMwOWMwOTQyNjE2MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V0FCvgi5ORxaDFvkdEMzjFXNp57y3sVH17vkzhadikY)
> @mtwente, what do you think?

I'll remove the line for media objects, ok? If they are images they are not supposed to have no thumbs anyway

2024-11-13 11:44 UTC, maehr commented
> > The reason for the missing derivates are manual uploads because of the file size. We should report this to @flicksolutions directly.
> 
> I just recreated all derivates on the new omeka server. The thumbnail generation fails these 4 tifs:
> 
> * 10722
> * 10723
>   -10953
>   -11413
> 
> I think the files might just be too large for the server to handle:
> 
> ```
> convert: width or height exceeds limit `/var/www/html/omeka-s-new/files/original/75d3863cda7afe2c253d7ff2c75b41b9f30e412f.tif' @ error/cache.c/OpenPixelCache/3911.
> convert: no images defined `/tmp/omekaOFSOEE.jpg' @ error/convert.c/ConvertImageCommand/3258.
> ```
> 
> Do you want me to look into that further?

Thank you very much for the swift reply. Can create the thumbnails manually and send them to you?

2024-11-13 14:00 UTC, flicksolutions commented
> > > The reason for the missing derivates are manual uploads because of the file size. We should report this to @flicksolutions directly.
> > 
> > 
> > I just recreated all derivates on the new omeka server. The thumbnail generation fails these 4 tifs:
> > 
> > * 10722
> > * 10723
> >   -10953
> >   -11413
> > 
> > I think the files might just be too large for the server to handle:
> > ```
> > convert: width or height exceeds limit `/var/www/html/omeka-s-new/files/original/75d3863cda7afe2c253d7ff2c75b41b9f30e412f.tif' @ error/cache.c/OpenPixelCache/3911.
> > convert: no images defined `/tmp/omekaOFSOEE.jpg' @ error/convert.c/ConvertImageCommand/3258.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you want me to look into that further?
> 
> Thank you very much for the swift reply. Can create the thumbnails manually and send them to you?

That's worth a try. sure, go ahead

2024-11-13 14:31 UTC, koilebeit approved these changes

2024-11-13 17:58 UTC, merged